//! Unity build for CCL tests

#define GTEST_LANG_CXX11 1

#include "gtest/gtest.h"

#include "../src/testTextData.cpp"
#include "../src/testRSConcept.cpp"
#include "../src/testSchema.cpp"
#include "../src/testTextConcept.cpp"
#include "../src/testThesaurus.cpp"
#include "../src/testConceptRecord.cpp"
#include "../src/testSource.cpp"
#include "../src/testCstNameGenerator.cpp"
#include "../src/testEntityContext.cpp"
#include "../src/testEntityGenerator.cpp"
#include "../src/testEnvironment.cpp"
#include "../src/testEquationOpts.cpp"
#include "../src/testEquationProcessor.cpp"
#include "../src/testExtractBasis.cpp"
#include "../src/testGenerator.cpp"
#include "../src/testInterpretationStorage.cpp"
#include "../src/testMaxPart.cpp"
#include "../src/testOSS.cpp"
#include "../src/testOperation.cpp"
#include "../src/testOSSComplex.cpp"
#include "../src/testOSSGraphFacet.cpp"
#include "../src/testOSSGridFacet.cpp"
#include "../src/testOSSOpsFacet.cpp"
#include "../src/testOSSSourceFacet.cpp"
#include "../src/testRelativation.cpp"
#include "../src/testRSAggregator.cpp"
#include "../src/testRSCalculationFacet.cpp"
#include "../src/testRSForm.cpp"
#include "../src/testRSCore.cpp"
#include "../src/testIdentityManager.cpp"
#include "../src/testCstList.cpp"
#include "../src/testCstType.cpp"
#include "../src/testRSModel.cpp"
#include "../src/testRSModsFacet.cpp"
#include "../src/testRSOperationsFacet.cpp"
#include "../src/testRSValuesFacet.cpp"
#include "../src/testSourceManager.cpp"
#include "../src/testSynthes.cpp"
#include "../src/testJSON.cpp"
#include "../src/testRSFormJA.cpp"