// AsciiLexerImpl.hpp generated by reflex 3.3.0 from src/AsciiLexerImpl.l

#define REFLEX_VERSION "3.3.0"

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  OPTIONS USED                                                              //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#undef REFLEX_OPTION_fast
#undef REFLEX_OPTION_lex
#undef REFLEX_OPTION_lexer
#undef REFLEX_OPTION_namespace
#undef REFLEX_OPTION_nodefault
#undef REFLEX_OPTION_noindent
#undef REFLEX_OPTION_noline
#undef REFLEX_OPTION_noyywrap
#undef REFLEX_OPTION_outfile
#undef REFLEX_OPTION_token_type

#define REFLEX_OPTION_fast                true
#define REFLEX_OPTION_lex                 lex
#define REFLEX_OPTION_lexer               AsciiLexerImpl
#define REFLEX_OPTION_namespace           ccl::rslang::asciilex
#define REFLEX_OPTION_nodefault           true
#define REFLEX_OPTION_noindent            true
#define REFLEX_OPTION_noline              true
#define REFLEX_OPTION_noyywrap            true
#define REFLEX_OPTION_outfile             "AsciiLexerImpl.hpp"
#define REFLEX_OPTION_token_type          ccl::rslang::TokenID

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 1: %top user code                                                 //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////



#pragma once
#include "ccl/rslang/RSToken.h"



////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  REGEX MATCHER                                                             //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#define WITH_NO_INDENT
#include <reflex/matcher.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  ABSTRACT LEXER CLASS                                                      //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/abslexer.h>

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  LEXER CLASS                                                               //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace ccl {
namespace rslang {
namespace asciilex {

class AsciiLexerImpl : public reflex::AbstractLexer<reflex::Matcher> {

public:
	[[nodiscard]] StrRange Range() const {
	 // Note: returning byte position, not code point! Assume input is ASCII
		return StrRange{ static_cast<StrPos>(matcher().first()),
						static_cast<StrPos>(matcher().last()) };
	}

 public:
  typedef reflex::AbstractLexer<reflex::Matcher> AbstractBaseLexer;
  AsciiLexerImpl(
      // a persistent source of input, empty by default
      const reflex::Input& input = reflex::Input(),
      // optional output stream, std::cout by default
      std::ostream& os = std::cout)
    :
      AbstractBaseLexer(input, os)
  {
  }
  static const int INITIAL = 0;
  // the lexer function defined by SECTION 2
  virtual ccl::rslang::TokenID lex(void);
  // lexer functions accepting new input to scan
  ccl::rslang::TokenID lex(const reflex::Input& input)
  {
    in(input);
    return lex();
  }
  ccl::rslang::TokenID lex(const reflex::Input& input, std::ostream *os)
  {
    in(input);
    if (os)
      out(*os);
    return lex();
  }
};

} // namespace ccl
} // namespace rslang
} // namespace asciilex

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  SECTION 2: rules                                                          //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

namespace ccl {
namespace rslang {
namespace asciilex {
extern void reflex_code_INITIAL(reflex::Matcher&);
} // namespace ccl
} // namespace rslang
} // namespace asciilex

ccl::rslang::TokenID ccl::rslang::asciilex::AsciiLexerImpl::lex(void)
{
  static const reflex::Pattern PATTERN_INITIAL(reflex_code_INITIAL);
  if (!has_matcher())
  {
    matcher(new Matcher(PATTERN_INITIAL, stdinit(), this));
  }
  while (true)
  {
        switch (matcher().scan())
        {
          case 0:
            if (matcher().at_end())
            {
{ return TokenID::END; }
            }
            else
            {
              lexer_error("scanner jammed");
              return ccl::rslang::TokenID();
            }
            break;
          case 1: // rule src/AsciiLexerImpl.l:45: "\A" :
{ return TokenID::FORALL; }
            break;
          case 2: // rule src/AsciiLexerImpl.l:46: "\E" :
{ return TokenID::EXISTS; }

            break;
          case 3: // rule src/AsciiLexerImpl.l:48: "\neg" :
{ return TokenID::NOT; }
            break;
          case 4: // rule src/AsciiLexerImpl.l:49: "&&" :
{ return TokenID::AND; }
            break;
          case 5: // rule src/AsciiLexerImpl.l:50: "||" :
{ return TokenID::OR; }
            break;
          case 6: // rule src/AsciiLexerImpl.l:51: "=>" :
{ return TokenID::IMPLICATION; }
            break;
          case 7: // rule src/AsciiLexerImpl.l:52: "<=>" :
{ return TokenID::EQUIVALENT; }

            break;
          case 8: // rule src/AsciiLexerImpl.l:54: "+" :
{ return TokenID::PLUS; }
            break;
          case 9: // rule src/AsciiLexerImpl.l:55: "-" :
{ return TokenID::MINUS; }
            break;
          case 10: // rule src/AsciiLexerImpl.l:56: "\multiply" :
{ return TokenID::MULTIPLY; }
            break;
          case 11: // rule src/AsciiLexerImpl.l:57: ">" :
{ return TokenID::GREATER; }
            break;
          case 12: // rule src/AsciiLexerImpl.l:58: "<" :
{ return TokenID::LESSER; }
            break;
          case 13: // rule src/AsciiLexerImpl.l:59: ">=" :
{ return TokenID::GREATER_OR_EQ; }
            break;
          case 14: // rule src/AsciiLexerImpl.l:60: "<=" :
{ return TokenID::LESSER_OR_EQ; }

            break;
          case 15: // rule src/AsciiLexerImpl.l:62: "=" :
{ return TokenID::EQUAL; }
            break;
          case 16: // rule src/AsciiLexerImpl.l:63: "!=" :
{ return TokenID::NOTEQUAL; }

            break;
          case 17: // rule src/AsciiLexerImpl.l:65: "\in" :
{ return TokenID::IN; }
            break;
          case 18: // rule src/AsciiLexerImpl.l:66: "\notin" :
{ return TokenID::NOTIN; }
            break;
          case 19: // rule src/AsciiLexerImpl.l:67: "\subseteq" :
{ return TokenID::SUBSET_OR_EQ; }
            break;
          case 20: // rule src/AsciiLexerImpl.l:68: "\subset" :
{ return TokenID::SUBSET; }
            break;
          case 21: // rule src/AsciiLexerImpl.l:69: "\notsubset" :
{ return TokenID::NOTSUBSET; }

            break;
          case 22: // rule src/AsciiLexerImpl.l:71: "*" :
{ return TokenID::DECART; }
            break;
          case 23: // rule src/AsciiLexerImpl.l:72: "\union" :
{ return TokenID::UNION; }
            break;
          case 24: // rule src/AsciiLexerImpl.l:73: "\intersect" :
{ return TokenID::INTERSECTION; }
            break;
          case 25: // rule src/AsciiLexerImpl.l:74: "\setminus" :
{ return TokenID::SET_MINUS; }
            break;
          case 26: // rule src/AsciiLexerImpl.l:75: "\symmdiff" :
{ return TokenID::SYMMINUS; }
            break;
          case 27: // rule src/AsciiLexerImpl.l:76: "B" :
{ return TokenID::BOOLEAN; }

            break;
          case 28: // rule src/AsciiLexerImpl.l:78: pr{index} :
{ return TokenID::SMALLPR; }
            break;
          case 29: // rule src/AsciiLexerImpl.l:79: Pr{index} :
{ return TokenID::BIGPR; }
            break;
          case 30: // rule src/AsciiLexerImpl.l:80: Fi{index} :
{ return TokenID::FILTER; }
            break;
          case 31: // rule src/AsciiLexerImpl.l:81: card :
{ return TokenID::CARD; }
            break;
          case 32: // rule src/AsciiLexerImpl.l:82: bool :
{ return TokenID::BOOL; }
            break;
          case 33: // rule src/AsciiLexerImpl.l:83: red :
{ return TokenID::REDUCE; }
            break;
          case 34: // rule src/AsciiLexerImpl.l:84: debool :
{ return TokenID::DEBOOL; }

            break;
          case 35: // rule src/AsciiLexerImpl.l:86: D :
{ return TokenID::DECLARATIVE; }
            break;
          case 36: // rule src/AsciiLexerImpl.l:87: R :
{ return TokenID::RECURSIVE; }
            break;
          case 37: // rule src/AsciiLexerImpl.l:88: I :
{ return TokenID::IMPERATIVE; }

            break;
          case 38: // rule src/AsciiLexerImpl.l:90: Z :
{ return TokenID::LIT_INTSET; }
            break;
          case 39: // rule src/AsciiLexerImpl.l:91: "{}" :
{ return TokenID::LIT_EMPTYSET; }
            break;
          case 40: // rule src/AsciiLexerImpl.l:92: {number} :
{ return TokenID::LIT_INTEGER; }

            break;
          case 41: // rule src/AsciiLexerImpl.l:94: F{number} :
{ return TokenID::ID_FUNCTION; }
            break;
          case 42: // rule src/AsciiLexerImpl.l:95: P{number} :
{ return TokenID::ID_PREDICATE; }
            break;
          case 43: // rule src/AsciiLexerImpl.l:96: R{number} :
{ return TokenID::ID_RADICAL; }

            break;
          case 44: // rule src/AsciiLexerImpl.l:98: {global_id} :
{ return TokenID::ID_GLOBAL; }
            break;
          case 45: // rule src/AsciiLexerImpl.l:99: {local_id} :
{ return TokenID::ID_LOCAL; }

            break;
          case 46: // rule src/AsciiLexerImpl.l:101: ":=" :
{ return TokenID::PUNC_ASSIGN; }
            break;
          case 47: // rule src/AsciiLexerImpl.l:102: "\from" :
{ return TokenID::PUNC_ITERATE; }
            break;
          case 48: // rule src/AsciiLexerImpl.l:103: ":==" :
{ return TokenID::PUNC_DEFINE; }
            break;
          case 49: // rule src/AsciiLexerImpl.l:104: "::=" :
{ return TokenID::PUNC_STRUCT; }
            break;
          case 50: // rule src/AsciiLexerImpl.l:105: "(" :
{ return TokenID::PUNC_PL; }
            break;
          case 51: // rule src/AsciiLexerImpl.l:106: ")" :
{ return TokenID::PUNC_PR; }
            break;
          case 52: // rule src/AsciiLexerImpl.l:107: "{" :
{ return TokenID::PUNC_CL; }
            break;
          case 53: // rule src/AsciiLexerImpl.l:108: "}" :
{ return TokenID::PUNC_CR; }
            break;
          case 54: // rule src/AsciiLexerImpl.l:109: "[" :
{ return TokenID::PUNC_SL; }
            break;
          case 55: // rule src/AsciiLexerImpl.l:110: "]" :
{ return TokenID::PUNC_SR; }
            break;
          case 56: // rule src/AsciiLexerImpl.l:111: "|" :
{ return TokenID::PUNC_BAR; }
            break;
          case 57: // rule src/AsciiLexerImpl.l:112: "," :
{ return TokenID::PUNC_COMMA; }
            break;
          case 58: // rule src/AsciiLexerImpl.l:113: ";" :
{ return TokenID::PUNC_SEMICOLON; }

            break;
          case 59: // rule src/AsciiLexerImpl.l:115: {ws} :
;
            break;
          case 60: // rule src/AsciiLexerImpl.l:117: . :
{ return TokenID::INTERRUPT; }

            break;
        }
  }
}

////////////////////////////////////////////////////////////////////////////////
//                                                                            //
//  TABLES                                                                    //
//                                                                            //
////////////////////////////////////////////////////////////////////////////////

#include <reflex/matcher.h>

#if defined(OS_WIN)
#pragma warning(disable:4101 4102)
#elif defined(__GNUC__)
#pragma GCC diagnostic ignored "-Wunused-variable"
#pragma GCC diagnostic ignored "-Wunused-label"
#elif defined(__clang__)
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-label"
#endif

namespace ccl {
namespace rslang {
namespace asciilex {

void reflex_code_INITIAL(reflex::Matcher& m)
{
  int c0 = 0, c1 = 0;
  m.FSM_INIT(c1);

S0:
  m.FSM_FIND();
  c1 = m.FSM_CHAR();
  if (c1 == '}') goto S172;
  if (c1 == '|') goto S53;
  if (c1 == '{') goto S149;
  if (c1 == 'r') goto S111;
  if (c1 == 'p') goto S76;
  if (c1 == 'd') goto S118;
  if (c1 == 'c') goto S97;
  if (c1 == 'b') goto S104;
  if ('a' <= c1 && c1 <= 'z') goto S158;
  if (c1 == '_') goto S158;
  if (c1 == ']') goto S176;
  if (c1 == '\\') goto S40;
  if (c1 == '[') goto S174;
  if (c1 == 'Z') goto S143;
  if (c1 == 'R') goto S131;
  if (c1 == 'P') goto S83;
  if (c1 == 'I') goto S137;
  if (c1 == 'F') goto S90;
  if (c1 == 'D') goto S125;
  if (c1 == 'B') goto S74;
  if ('A' <= c1 && c1 <= 'Y') goto S152;
  if (c1 == '>') goto S66;
  if (c1 == '=') goto S56;
  if (c1 == '<') goto S59;
  if (c1 == ';') goto S180;
  if (c1 == ':') goto S164;
  if ('0' <= c1 && c1 <= '9') goto S184;
  if (c1 == '-') goto S64;
  if (c1 == ',') goto S178;
  if (c1 == '+') goto S62;
  if (c1 == '*') goto S72;
  if (c1 == ')') goto S170;
  if (c1 == '(') goto S168;
  if (c1 == '&') goto S50;
  if (c1 == '!') goto S69;
  if (c1 == ' ') goto S187;
  if (c1 == '\r') goto S187;
  if (c1 == '\n') goto S192;
  if (c1 == '\t') goto S187;
  if (0 <= c1) goto S182;
  return m.FSM_HALT(c1);

S40:
  m.FSM_TAKE(60);
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S212;
  if (c1 == 's') goto S208;
  if (c1 == 'n') goto S201;
  if (c1 == 'm') goto S204;
  if (c1 == 'i') goto S206;
  if (c1 == 'f') goto S214;
  if (c1 == 'E') goto S199;
  if (c1 == 'A') goto S197;
  return m.FSM_HALT(c1);

S50:
  m.FSM_TAKE(60);
  c1 = m.FSM_CHAR();
  if (c1 == '&') goto S216;
  return m.FSM_HALT(c1);

S53:
  m.FSM_TAKE(56);
  c1 = m.FSM_CHAR();
  if (c1 == '|') goto S218;
  return m.FSM_HALT(c1);

S56:
  m.FSM_TAKE(15);
  c1 = m.FSM_CHAR();
  if (c1 == '>') goto S220;
  return m.FSM_HALT(c1);

S59:
  m.FSM_TAKE(12);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S222;
  return m.FSM_HALT(c1);

S62:
  m.FSM_TAKE(8);
  return m.FSM_HALT();

S64:
  m.FSM_TAKE(9);
  return m.FSM_HALT();

S66:
  m.FSM_TAKE(11);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S225;
  return m.FSM_HALT(c1);

S69:
  m.FSM_TAKE(60);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S227;
  return m.FSM_HALT(c1);

S72:
  m.FSM_TAKE(22);
  return m.FSM_HALT();

S74:
  m.FSM_TAKE(27);
  return m.FSM_HALT();

S76:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S229;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S83:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S241;
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S247;
  return m.FSM_HALT(c1);

S90:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S259;
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S265;
  return m.FSM_HALT(c1);

S97:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if ('b' <= c1 && c1 <= 'z') goto S235;
  if (c1 == 'a') goto S271;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S104:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S278;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S111:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S285;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S118:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S292;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S125:
  m.FSM_TAKE(35);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S253;
  return m.FSM_HALT(c1);

S131:
  m.FSM_TAKE(36);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S299;
  return m.FSM_HALT(c1);

S137:
  m.FSM_TAKE(37);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S253;
  return m.FSM_HALT(c1);

S143:
  m.FSM_TAKE(38);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S253;
  return m.FSM_HALT(c1);

S149:
  m.FSM_TAKE(52);
  c1 = m.FSM_CHAR();
  if (c1 == '}') goto S305;
  return m.FSM_HALT(c1);

S152:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S253;
  return m.FSM_HALT(c1);

S158:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S164:
  m.FSM_TAKE(60);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S307;
  if (c1 == ':') goto S310;
  return m.FSM_HALT(c1);

S168:
  m.FSM_TAKE(50);
  return m.FSM_HALT();

S170:
  m.FSM_TAKE(51);
  return m.FSM_HALT();

S172:
  m.FSM_TAKE(53);
  return m.FSM_HALT();

S174:
  m.FSM_TAKE(54);
  return m.FSM_HALT();

S176:
  m.FSM_TAKE(55);
  return m.FSM_HALT();

S178:
  m.FSM_TAKE(57);
  return m.FSM_HALT();

S180:
  m.FSM_TAKE(58);
  return m.FSM_HALT();

S182:
  m.FSM_TAKE(60);
  return m.FSM_HALT();

S184:
  m.FSM_TAKE(40);
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S312;
  return m.FSM_HALT(c1);

S187:
  m.FSM_TAKE(59);
  c1 = m.FSM_CHAR();
  if (c1 == ' ') goto S192;
  if (c1 == '\r') goto S192;
  if ('\t' <= c1 && c1 <= '\n') goto S192;
  return m.FSM_HALT(c1);

S192:
  m.FSM_TAKE(59);
  c1 = m.FSM_CHAR();
  if (c1 == ' ') goto S192;
  if (c1 == '\r') goto S192;
  if ('\t' <= c1 && c1 <= '\n') goto S192;
  return m.FSM_HALT(c1);

S197:
  m.FSM_TAKE(1);
  return m.FSM_HALT();

S199:
  m.FSM_TAKE(2);
  return m.FSM_HALT();

S201:
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S317;
  if (c1 == 'e') goto S315;
  return m.FSM_HALT(c1);

S204:
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S319;
  return m.FSM_HALT(c1);

S206:
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S321;
  return m.FSM_HALT(c1);

S208:
  c1 = m.FSM_CHAR();
  if (c1 == 'y') goto S328;
  if (c1 == 'u') goto S324;
  if (c1 == 'e') goto S326;
  return m.FSM_HALT(c1);

S212:
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S330;
  return m.FSM_HALT(c1);

S214:
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S332;
  return m.FSM_HALT(c1);

S216:
  m.FSM_TAKE(4);
  return m.FSM_HALT();

S218:
  m.FSM_TAKE(5);
  return m.FSM_HALT();

S220:
  m.FSM_TAKE(6);
  return m.FSM_HALT();

S222:
  m.FSM_TAKE(14);
  c1 = m.FSM_CHAR();
  if (c1 == '>') goto S334;
  return m.FSM_HALT(c1);

S225:
  m.FSM_TAKE(13);
  return m.FSM_HALT();

S227:
  m.FSM_TAKE(16);
  return m.FSM_HALT();

S229:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S336;
  return m.FSM_HALT(c1);

S235:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S241:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S343;
  return m.FSM_HALT(c1);

S247:
  m.FSM_TAKE(42);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S247;
  return m.FSM_HALT(c1);

S253:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S253;
  return m.FSM_HALT(c1);

S259:
  m.FSM_TAKE(44);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S350;
  return m.FSM_HALT(c1);

S265:
  m.FSM_TAKE(41);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S265;
  return m.FSM_HALT(c1);

S271:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S357;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S278:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S364;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S285:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'd') goto S371;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S292:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'b') goto S377;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S299:
  m.FSM_TAKE(43);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S299;
  return m.FSM_HALT(c1);

S305:
  m.FSM_TAKE(39);
  return m.FSM_HALT();

S307:
  m.FSM_TAKE(46);
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S384;
  return m.FSM_HALT(c1);

S310:
  c1 = m.FSM_CHAR();
  if (c1 == '=') goto S386;
  return m.FSM_HALT(c1);

S312:
  m.FSM_TAKE(40);
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S312;
  return m.FSM_HALT(c1);

S315:
  c1 = m.FSM_CHAR();
  if (c1 == 'g') goto S388;
  return m.FSM_HALT(c1);

S317:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S390;
  return m.FSM_HALT(c1);

S319:
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S393;
  return m.FSM_HALT(c1);

S321:
  m.FSM_TAKE(17);
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S395;
  return m.FSM_HALT(c1);

S324:
  c1 = m.FSM_CHAR();
  if (c1 == 'b') goto S397;
  return m.FSM_HALT(c1);

S326:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S399;
  return m.FSM_HALT(c1);

S328:
  c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S401;
  return m.FSM_HALT(c1);

S330:
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S403;
  return m.FSM_HALT(c1);

S332:
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S405;
  return m.FSM_HALT(c1);

S334:
  m.FSM_TAKE(7);
  return m.FSM_HALT();

S336:
  m.FSM_TAKE(28);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S336;
  if (c1 == ',') goto S407;
  return m.FSM_HALT(c1);

S343:
  m.FSM_TAKE(29);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S343;
  if (c1 == ',') goto S409;
  return m.FSM_HALT(c1);

S350:
  m.FSM_TAKE(30);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S253;
  if (c1 == '_') goto S253;
  if ('A' <= c1 && c1 <= 'Z') goto S253;
  if ('0' <= c1 && c1 <= '9') goto S350;
  if (c1 == ',') goto S411;
  return m.FSM_HALT(c1);

S357:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'd') goto S413;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S364:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S419;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S371:
  m.FSM_TAKE(33);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S377:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S425;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S384:
  m.FSM_TAKE(48);
  return m.FSM_HALT();

S386:
  m.FSM_TAKE(49);
  return m.FSM_HALT();

S388:
  m.FSM_TAKE(3);
  return m.FSM_HALT();

S390:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S434;
  if (c1 == 'i') goto S432;
  return m.FSM_HALT(c1);

S393:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S436;
  return m.FSM_HALT(c1);

S395:
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S438;
  return m.FSM_HALT(c1);

S397:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S440;
  return m.FSM_HALT(c1);

S399:
  c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S442;
  return m.FSM_HALT(c1);

S401:
  c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S444;
  return m.FSM_HALT(c1);

S403:
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S446;
  return m.FSM_HALT(c1);

S405:
  c1 = m.FSM_CHAR();
  if (c1 == 'm') goto S448;
  return m.FSM_HALT(c1);

S407:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S450;
  return m.FSM_HALT(c1);

S409:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S454;
  return m.FSM_HALT(c1);

S411:
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S458;
  return m.FSM_HALT(c1);

S413:
  m.FSM_TAKE(31);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S419:
  m.FSM_TAKE(32);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S425:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'o') goto S462;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S432:
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S469;
  return m.FSM_HALT(c1);

S434:
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S471;
  return m.FSM_HALT(c1);

S436:
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S473;
  return m.FSM_HALT(c1);

S438:
  c1 = m.FSM_CHAR();
  if (c1 == 'r') goto S475;
  return m.FSM_HALT(c1);

S440:
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S477;
  return m.FSM_HALT(c1);

S442:
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S479;
  return m.FSM_HALT(c1);

S444:
  c1 = m.FSM_CHAR();
  if (c1 == 'd') goto S481;
  return m.FSM_HALT(c1);

S446:
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S483;
  return m.FSM_HALT(c1);

S448:
  m.FSM_TAKE(47);
  return m.FSM_HALT();

S450:
  m.FSM_TAKE(28);
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S450;
  if (c1 == ',') goto S407;
  return m.FSM_HALT(c1);

S454:
  m.FSM_TAKE(29);
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S454;
  if (c1 == ',') goto S409;
  return m.FSM_HALT(c1);

S458:
  m.FSM_TAKE(30);
  c1 = m.FSM_CHAR();
  if ('0' <= c1 && c1 <= '9') goto S458;
  if (c1 == ',') goto S411;
  return m.FSM_HALT(c1);

S462:
  m.FSM_TAKE(45);
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S485;
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S469:
  m.FSM_TAKE(18);
  return m.FSM_HALT();

S471:
  c1 = m.FSM_CHAR();
  if (c1 == 'b') goto S491;
  return m.FSM_HALT(c1);

S473:
  c1 = m.FSM_CHAR();
  if (c1 == 'p') goto S493;
  return m.FSM_HALT(c1);

S475:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S495;
  return m.FSM_HALT(c1);

S477:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S497;
  return m.FSM_HALT(c1);

S479:
  c1 = m.FSM_CHAR();
  if (c1 == 'n') goto S500;
  return m.FSM_HALT(c1);

S481:
  c1 = m.FSM_CHAR();
  if (c1 == 'i') goto S502;
  return m.FSM_HALT(c1);

S483:
  m.FSM_TAKE(23);
  return m.FSM_HALT();

S485:
  m.FSM_TAKE(34);
  c1 = m.FSM_CHAR();
  if ('a' <= c1 && c1 <= 'z') goto S235;
  if (c1 == '_') goto S235;
  if ('A' <= c1 && c1 <= 'Z') goto S235;
  if ('0' <= c1 && c1 <= '9') goto S235;
  return m.FSM_HALT(c1);

S491:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S504;
  return m.FSM_HALT(c1);

S493:
  c1 = m.FSM_CHAR();
  if (c1 == 'l') goto S506;
  return m.FSM_HALT(c1);

S495:
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S508;
  return m.FSM_HALT(c1);

S497:
  m.FSM_TAKE(20);
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S510;
  return m.FSM_HALT(c1);

S500:
  c1 = m.FSM_CHAR();
  if (c1 == 'u') goto S512;
  return m.FSM_HALT(c1);

S502:
  c1 = m.FSM_CHAR();
  if (c1 == 'f') goto S514;
  return m.FSM_HALT(c1);

S504:
  c1 = m.FSM_CHAR();
  if (c1 == 'e') goto S516;
  return m.FSM_HALT(c1);

S506:
  c1 = m.FSM_CHAR();
  if (c1 == 'y') goto S518;
  return m.FSM_HALT(c1);

S508:
  c1 = m.FSM_CHAR();
  if (c1 == 'c') goto S520;
  return m.FSM_HALT(c1);

S510:
  c1 = m.FSM_CHAR();
  if (c1 == 'q') goto S522;
  return m.FSM_HALT(c1);

S512:
  c1 = m.FSM_CHAR();
  if (c1 == 's') goto S524;
  return m.FSM_HALT(c1);

S514:
  c1 = m.FSM_CHAR();
  if (c1 == 'f') goto S526;
  return m.FSM_HALT(c1);

S516:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S528;
  return m.FSM_HALT(c1);

S518:
  m.FSM_TAKE(10);
  return m.FSM_HALT();

S520:
  c1 = m.FSM_CHAR();
  if (c1 == 't') goto S530;
  return m.FSM_HALT(c1);

S522:
  m.FSM_TAKE(19);
  return m.FSM_HALT();

S524:
  m.FSM_TAKE(25);
  return m.FSM_HALT();

S526:
  m.FSM_TAKE(26);
  return m.FSM_HALT();

S528:
  m.FSM_TAKE(21);
  return m.FSM_HALT();

S530:
  m.FSM_TAKE(24);
  return m.FSM_HALT();
}

} // namespace ccl

} // namespace rslang

} // namespace asciilex

